### ISSUE TITLE
论文结果复现

### ISSUE THREAD

**Issue by oooo111** [hannshu/stCluster#2]
作者您好，我在复现stcluster的过程中，使用示例151507按照文档复现，得到的ARI结果是0.26，但您的文档给出的ARI是0.645，请问是哪个超参数没设置到吗。

**Comment by caoname** [comment]
请问你这个ARI结果最终运行的结果跟原文一样吗

**Comment by hannshu** [comment]
[caoname](https://github.com/caoname)你好，你可以尝试通过dockerhub (https://hub.docker.com/r/hannshu/stcluster) 上已经配置好的环境，数据，以及训练好的模型参数复现原文中的结果。

**Comment by caoname** [comment]
感谢您的回答！
